from __future__ import annotations

import json
import os
from typing import Any, Dict, List


SYSTEM_PROMPT = (
    "You are an autonomous software creator. "
    "Return ONLY valid JSON: {\"plan\": [ ... ], \"critique\": \"...\"}. "
    "Each plan item must be {\"action\": \"create_file\", \"path\": \"...\", \"content\": \"...\"}."
)


class LLMReasoner:
    def __init__(self, enabled: bool = False) -> None:
        self.enabled = enabled and bool(os.getenv("OPENAI_API_KEY"))

    def think(self, goal: str, previous_critique: str = "") -> Dict[str, Any]:
        if not self.enabled:
            return self._fallback(goal, previous_critique)

        try:
            from openai import OpenAI  # type: ignore

            client = OpenAI()
            user_prompt = (
                f"Goal: {goal}\n"
                f"Previous critique: {previous_critique or 'None'}\n"
                "Generate a concise plan with 2-5 create_file actions."
            )
            resp = client.responses.create(
                model="gpt-4.1-mini",
                input=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
            )
            text = resp.output_text.strip()
            return json.loads(text)
        except Exception:
            return self._fallback(goal, previous_critique)

    def _fallback(self, goal: str, previous_critique: str = "") -> Dict[str, Any]:
        idea = goal.lower()
        if "website" in idea or "portfolio" in idea:
            plan: List[Dict[str, str]] = [
                {
                    "action": "create_file",
                    "path": "index.html",
                    "content": """<!doctype html>
<html>
  <head><meta charset='utf-8'><title>Generated Site</title></head>
  <body>
    <h1>Generated by Autonomous Creator Bot</h1>
    <p>This site was created from a high-level goal.</p>
  </body>
</html>
""",
                },
                {
                    "action": "create_file",
                    "path": "style.css",
                    "content": "body { font-family: Arial, sans-serif; margin: 2rem; }",
                },
                {
                    "action": "create_file",
                    "path": "README.md",
                    "content": f"# Generated Project\n\nGoal: {goal}\n",
                },
            ]
        else:
            plan = [
                {
                    "action": "create_file",
                    "path": "README.md",
                    "content": f"# Generated Project\n\nGoal: {goal}\n",
                },
                {
                    "action": "create_file",
                    "path": "main.py",
                    "content": """def main() -> None:
    print('Generated by Autonomous Creator Bot')


if __name__ == '__main__':
    main()
""",
                },
                {
                    "action": "create_file",
                    "path": "requirements.txt",
                    "content": "",
                },
            ]

        critique = (
            "Previous critique applied in this iteration."
            if previous_critique
            else "Initial draft generated."
        )
        return {"plan": plan, "critique": critique}
